# fly.toml app configuration file generated for rss-proxy-api-flyp on 2025-03-19T17:20:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rss-proxy-api'
primary_region = 'ams'

[build]

[env]
  JAVA_OPTS = '-XX:MaxRAM=512m'
  SPRING_PROFILES_ACTIVE = 'production'

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[http_service.headers]]
    for = "/*"
    [http_service.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      Content-Security-Policy = "default-src 'self'"
      Referrer-Policy = "strict-origin-when-cross-origin"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
